### ISSUE TITLE
Correct value for UDP listening state?

### ISSUE THREAD

**Issue by acheronfail** [mattsta/netmatt#1]
Unless I'm mistaken, I believe you should be checking for `cxn[3] == "01"` here instead of `"07"`: https://github.com/mattsta/netmatt/blob/ed7a1eab963ea883fcfa04be477a0cd942f3bd49/net-listeners-unified.py#L148

If I understand this right (which I may not) then `"01"` (which is `TCP_ESTABLISHED`) would reflect a "listening" state, and `"07"` would reflect the closed state.

https://github.com/torvalds/linux/blob/386403a115f95997c2715691226e11a7b5cffcfd/net/ipv4/udp.c#L1846-L1853

I may misunderstand UDP completely, though. :laughing:

**Comment by mattsta** [comment]
Yeah, it's a bit confusing, but `07` is correct here.

Since UDP doesn't have connections, it doesn't technically have a "listen" state, so Linux re-uses the `TCP_CLOSED` value for UDP sockets waiting for inbound packets. (because, i guess technically it is "closed to TCP")

You are correct about `01` being the correct value for active UDP sockets, but the tool only cares about showing which servers are currently in an accepting/listening state.

You can see the original netstat source code uses the same conversion of `TCP_CLOSE` (represented as `07` in `/proc/net/udp` output) to mean "UDP Socket open for connections" (which gets shown as... nothing output since "listening" and "closed" aren't valid UDP states): https://github.com/ecki/net-tools/blob/master/netstat.c#L1286-L1298

**Comment by acheronfail** [comment]
Ah, I suppose that makes sense. 

Thanks for clearing that up! 😊
